---
all:
  children:
    panel:
      hosts:
        remnawave_panel:
          ansible_host: "192.168.1.1"  # unique from node ips
      vars:
        remnawave_panel_domain: "example.com"
        remnawave_secret_header_enabled: true
        monitoring_server_ip: "{{ hostvars[groups['monitoring'][0]]['ansible_host'] }}"  # ← do not change

    nodes:
      hosts:
        node_msk:  # unique
          ansible_host: "192.168.0.1"  # unique, must be different from panel ip
          node_name: "msk"  # unique, 3 chars minimum
          node_port: 2222  # avoid 22, 80, 443, 8443, 61000
          node_domain: "node.example.com" # unique
      
      vars:
        # ↓ do not change ↓
        node_address: "{{ ansible_host }}"
        panel_ip: "{{ hostvars[groups['panel'][0]]['ansible_host'] }}"
        remnawave_panel_domain: "{{ hostvars[groups['panel'][0]]['remnawave_panel_domain'] }}"
        monitoring_server_ip: "{{ hostvars[groups['monitoring'][0]]['ansible_host'] }}"
        # ↑ do not change ↑

    monitoring:
      hosts:
        monitoring_server:
          ansible_host: "192.168.2.1"  # unique from panel & node ips
      vars:
        monitoring_server_ip: "{{ ansible_host }}"
        prometheus_port: 9090
        grafana_port: 3000
        whitebox_port: 9116
        blackbox_port: 9115
        allowed_ports:    # overrides the same var below. do not change
          - "{{ ansible_port }}"

  vars:
    ssh_user: "root"
    ssh_key: "~/.ssh/id_ed25519"  # leave empty if using password
    ssh_password: ""  # leave empty if using key
    ansible_port: 22  # ssh port to connect to
    acmesh_email: ""  # used by acme.sh (tls certs), optional. defaults to admin@example.com

    # security settings
    ssh_permit_root_login: "prohibit-password"  # change if using password
    ssh_password_authentication: "no"
    ssh_max_auth_tries: 3
    ssh_login_grace_time: 30  # seconds
    fail2ban_enabled: yes
    fail2ban_maxretry: 3
    fail2ban_bantime: 86400  # seconds
    auto_updates_enabled: yes

    # ↓ do not change ↓
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_private_key_file: "{{ ssh_key }}"
    ansible_ssh_pass: "{{ ssh_password }}"
    acmesh_port: 8443
    allowed_ports:
      - "{{ ansible_port }}"
      - 80
      - 443
    # ↑ do not change ↑