---
- name: restart docker
  systemd:
    name: docker
    state: restarted
    enabled: true

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: true

- name: reload ufw
  community.general.ufw:
    state: reloaded
  become: yes
